service: rust-serverless
provider:
  name: aws
  runtime: rust
  memorySize: 128

package:
  individually: true

plugins:
  - serverless-rust

functions:
  hello:
    handler: hello
    events:
      - http:
          path: '/'
          method: GET
